### PR TITLE
Add cpp linter and fix warnings

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Add cpp linter and fix warnings
It is using Google style to format the ``C++`` code, but if you want to I can change it to another style :)
For now it is just using ``clang-format`` to format the code and ``cpplint`` to do some simple static analysis (but I am skipping some rules: ``-readability/todo,-build/header_guard,-build/c++11,-runtime/references,-runtime/explicit``)

### CODE REVIEW

**Comment by wolfv** [comment]
https://github.com/xtensor-stack/xtensor/issues/1266

**Comment by marcelotrevisani** [comment]
> [xtensor-stack/xtensor#1266](https://github.com/xtensor-stack/xtensor/issues/1266)

Nice, I am going to change it then

**Comment by wolfv** [comment]
looks like we didn't do a good job of including everything that's needed! sorry about that

**Comment by wolfv** [comment]
awesome!

**Pull request merged**
